version: "3.8"
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.linux
    ports:
      - "8000:8000"
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    depends_on:
      - proxy
    tty: true
    volumes:
      - /app/node_modules
      - .:/app